name:                lukcal
version:             0.1.0.0
github:              "dee-me-tree-or-love/happy-and-alex-typed-lukcal"
license:             BSD3
author:              "D O"
maintainer:          "dee-me-tree-or-love"
copyright:           "2023 D O"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dee-me-tree-or-love/happy-and-alex-typed-lukcal#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - cmdargs
    - array
    - base
    - bytestring
  build-tools:
    - alex
    - happy

executables:
  lukcal-cli:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lukcal

tests:
  lukcal-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lukcal
